---
delay: 8
wowpath: "/home/username/.wine/drive_c/Program Files (x86)/World of Warcraft/Wow.exe"
wineprefix: "/home/username/.wine"

accounts:
  - name: 'main'
    username: 'mainaccount'
    password: 'somepassword'

  - name: 'second'
    username: 'secondaccount'
    password: 'someotherpassword'
